port: 8000
dev: false
website: "x.x.x.x:5000" #the Register Server's ip or domain ,just for page show
account:
  user: "admin"
  pass: "1"
  resetOnRestart: true
db:
  driver: mysql
  connect: "root:12345678@tcp(127.0.0.1:3306)/open-auth"
redis:
  client:
    addr: "localhost:6379"
    pass: ""
    db: 0
redis_cache_from_db: true #从数据库读取数据，写入缓存，仅用于迁移redis后使用
open_register: true #是否开放用户注册
open_app_register: true #是否开放app注册
